#define UNICODE
#define _UNICODE
#define NOMINMAX

#include <windows.h>
#include <commctrl.h>
#include <shobjidl.h>
#include <shellapi.h>
#include <urlmon.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#pragma comment(lib, "Comctl32.lib")
#pragma comment(lib, "Shell32.lib")
#pragma comment(lib, "Ole32.lib")
#pragma comment(lib, "Urlmon.lib")

namespace fs = std::filesystem;

namespace {
constexpr int IDC_ROOT_COMBO = 1001;
constexpr int IDC_BROWSE = 1002;
constexpr int IDC_CHECK_ROOT = 1003;
constexpr int IDC_START_INDEX = 1004;
constexpr int IDC_STOP_INDEX = 1005;
constexpr int IDC_QUERY = 1006;
constexpr int IDC_ONLY_NAME = 1007;
constexpr int IDC_CASE = 1008;
constexpr int IDC_SEARCH = 1009;
constexpr int IDC_CLEAR = 1010;
constexpr int IDC_RESULTS = 1011;
constexpr int IDC_STATUS = 1012;
constexpr int IDC_TABS = 1013;
constexpr int IDC_OPEN_FILE = 1014;
constexpr int IDC_OPEN_FOLDER = 1015;
constexpr int IDC_COPY_PATH = 1016;
constexpr UINT WM_APP_INDEX_DONE = WM_APP + 10;
constexpr UINT WM_APP_SEARCH_DONE = WM_APP + 11;

struct ResultItem { std::wstring name, path, size, type, modified; };
struct AppState {
    HINSTANCE instance{}; HWND mainWindow{};
    HWND rootGroup{}, rootCombo{}, browseButton{}, checkRootButton{}, rootStatus{};
    HWND indexGroup{}, startIndexButton{}, stopIndexButton{};
    HWND tabs{}, queryLabel{}, queryEdit{}, onlyNameCheck{}, caseCheck{}, searchButton{}, clearButton{};
    HWND results{}, statusBar{}; HFONT uiFont{}; int dpi = 96;
    fs::path appDir, dataDir, logsDir, indexPath, resultsPath, rootPathFile, settingsFile, guiLogFile;
    std::vector<ResultItem> currentResults;
};
AppState g_app;

int scale(int value) { return MulDiv(value, g_app.dpi, 96); }
std::string wideToUtf8(const std::wstring& value) { if (value.empty()) return {}; int len = WideCharToMultiByte(CP_UTF8,0,value.data(),(int)value.size(),nullptr,0,nullptr,nullptr); if(len<=0) return {}; std::string out((size_t)len,'\0'); WideCharToMultiByte(CP_UTF8,0,value.data(),(int)value.size(),out.data(),len,nullptr,nullptr); return out; }
std::wstring utf8ToWide(const std::string& value) { if (value.empty()) return {}; int len = MultiByteToWideChar(CP_UTF8,0,value.data(),(int)value.size(),nullptr,0); if(len<=0) return {}; std::wstring out((size_t)len,L'\0'); MultiByteToWideChar(CP_UTF8,0,value.data(),(int)value.size(),out.data(),len); return out; }
std::wstring quote(const std::wstring& v) { return L"\"" + v + L"\""; }
fs::path exeDir() { std::array<wchar_t,32768> b{}; DWORD n=GetModuleFileNameW(nullptr,b.data(),(DWORD)b.size()); return n?fs::path(std::wstring(b.data(),n)).parent_path():fs::current_path(); }
void ensureDirs(){ g_app.dataDir=g_app.appDir/L"data"; g_app.logsDir=g_app.appDir/L"logs"; g_app.indexPath=g_app.dataDir/L"file_index.ffdb"; g_app.resultsPath=g_app.dataDir/L"search_results.tsv"; g_app.rootPathFile=g_app.dataDir/L"index_root.txt"; g_app.settingsFile=g_app.dataDir/L"settings.txt"; g_app.guiLogFile=g_app.logsDir/L"gui.log"; fs::create_directories(g_app.dataDir); fs::create_directories(g_app.logsDir); }
void logLine(const std::wstring& m){ try{ std::ofstream log(g_app.guiLogFile,std::ios::binary|std::ios::app); if(!log) return; SYSTEMTIME st{}; GetLocalTime(&st); wchar_t p[64]{}; swprintf_s(p,L"%04u-%02u-%02u %02u:%02u:%02u ",st.wYear,st.wMonth,st.wDay,st.wHour,st.wMinute,st.wSecond); log<<wideToUtf8(p)<<wideToUtf8(m)<<"\r\n"; }catch(...){}}
void setStatus(const std::wstring& t){ if(g_app.statusBar) SetWindowTextW(g_app.statusBar,t.c_str()); }
void setRootStatus(const std::wstring& t){ if(g_app.rootStatus) SetWindowTextW(g_app.rootStatus,t.c_str()); }
void showError(const std::wstring& t){ MessageBoxW(g_app.mainWindow,t.c_str(),L"FindFile",MB_ICONERROR|MB_OK); }
void showInfo(const std::wstring& t){ MessageBoxW(g_app.mainWindow,t.c_str(),L"FindFile",MB_ICONINFORMATION|MB_OK); }
std::wstring getText(HWND h){ int len=GetWindowTextLengthW(h); std::wstring t((size_t)len,L'\0'); if(len>0) GetWindowTextW(h,t.data(),len+1); return t; }
void setText(HWND h,const std::wstring& t){ SetWindowTextW(h,t.c_str()); }
HFONT createSystemFont(){ NONCLIENTMETRICSW m{}; m.cbSize=sizeof(m); SystemParametersInfoW(SPI_GETNONCLIENTMETRICS,sizeof(m),&m,0); return CreateFontIndirectW(&m.lfMessageFont); }
void applyFont(HWND h){ if(h&&g_app.uiFont) SendMessageW(h,WM_SETFONT,(WPARAM)g_app.uiFont,TRUE); }
void applyFonts(){ for(HWND h:{g_app.rootGroup,g_app.rootCombo,g_app.browseButton,g_app.checkRootButton,g_app.rootStatus,g_app.indexGroup,g_app.startIndexButton,g_app.stopIndexButton,g_app.tabs,g_app.queryLabel,g_app.queryEdit,g_app.onlyNameCheck,g_app.caseCheck,g_app.searchButton,g_app.clearButton,g_app.results,g_app.statusBar}) applyFont(h); }
void recreateFont(){ if(g_app.uiFont) DeleteObject(g_app.uiFont); g_app.uiFont=createSystemFont(); applyFonts(); }
void addComboItem(const std::wstring& v){ if(v.empty()) return; LRESULT c=SendMessageW(g_app.rootCombo,CB_GETCOUNT,0,0); for(LRESULT i=0;i<c;++i){ wchar_t b[32768]{}; SendMessageW(g_app.rootCombo,CB_GETLBTEXT,(WPARAM)i,(LPARAM)b); if(_wcsicmp(b,v.c_str())==0) return;} SendMessageW(g_app.rootCombo,CB_ADDSTRING,0,(LPARAM)v.c_str()); }
void saveTextFile(const fs::path& p,const std::wstring& v){ std::ofstream o(p,std::ios::binary|std::ios::trunc); o<<wideToUtf8(v); }
std::wstring readTextFile(const fs::path& p){ std::ifstream in(p,std::ios::binary); if(!in) return {}; std::string d((std::istreambuf_iterator<char>(in)),{}); return utf8ToWide(d); }
void loadSettings(){ std::ifstream in(g_app.settingsFile,std::ios::binary); if(!in) return; std::string line; bool first=true; while(std::getline(in,line)){ if(!line.empty()&&line.back()=='\r') line.pop_back(); auto p=utf8ToWide(line); if(p.empty()) continue; addComboItem(p); if(first){ setText(g_app.rootCombo,p); first=false; } } }
void saveSettings(){ std::wstring cur=getText(g_app.rootCombo); std::vector<std::wstring> paths; if(!cur.empty()) paths.push_back(cur); LRESULT c=SendMessageW(g_app.rootCombo,CB_GETCOUNT,0,0); for(LRESULT i=0;i<c && paths.size()<20;++i){ wchar_t b[32768]{}; SendMessageW(g_app.rootCombo,CB_GETLBTEXT,(WPARAM)i,(LPARAM)b); std::wstring v=b; if(v.empty()) continue; bool exists=false; for(auto& e:paths) if(_wcsicmp(e.c_str(),v.c_str())==0) exists=true; if(!exists) paths.push_back(v);} std::ofstream out(g_app.settingsFile,std::ios::binary|std::ios::trunc); for(auto& p:paths) out<<wideToUtf8(p)<<"\n"; }
std::wstring pickFolder(){ IFileOpenDialog* d=nullptr; if(FAILED(CoCreateInstance(CLSID_FileOpenDialog,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&d)))||!d) return {}; DWORD opt=0; d->GetOptions(&opt); d->SetOptions(opt|FOS_PICKFOLDERS|FOS_FORCEFILESYSTEM); d->SetTitle(L"Выберите папку для индексации"); std::wstring r; if(SUCCEEDED(d->Show(g_app.mainWindow))){ IShellItem* item=nullptr; if(SUCCEEDED(d->GetResult(&item))&&item){ PWSTR path=nullptr; if(SUCCEEDED(item->GetDisplayName(SIGDN_FILESYSPATH,&path))&&path){ r=path; CoTaskMemFree(path);} item->Release();}} d->Release(); return r; }
bool runProcessWait(const std::wstring& commandLine,DWORD* exitCode=nullptr,bool hidden=true){ STARTUPINFOW si{}; si.cb=sizeof(si); if(hidden){ si.dwFlags=STARTF_USESHOWWINDOW; si.wShowWindow=SW_HIDE;} PROCESS_INFORMATION pi{}; std::wstring cmd=commandLine; logLine(L"RUN: "+cmd); if(!CreateProcessW(nullptr,cmd.data(),nullptr,nullptr,FALSE,hidden?CREATE_NO_WINDOW:0,nullptr,g_app.appDir.c_str(),&si,&pi)){ DWORD e=GetLastError(); logLine(L"CreateProcess failed: "+std::to_wstring(e)); if(exitCode) *exitCode=e; return false;} WaitForSingleObject(pi.hProcess,INFINITE); DWORD code=0; GetExitCodeProcess(pi.hProcess,&code); CloseHandle(pi.hThread); CloseHandle(pi.hProcess); logLine(L"EXIT: "+std::to_wstring(code)); if(exitCode) *exitCode=code; return code==0; }
void clearResults(){ ListView_DeleteAllItems(g_app.results); g_app.currentResults.clear(); setStatus(L"Готово"); }
void addResultToList(const ResultItem& it,int row){ LVITEMW lvi{}; lvi.mask=LVIF_TEXT; lvi.iItem=row; lvi.iSubItem=0; lvi.pszText=(LPWSTR)it.name.c_str(); ListView_InsertItem(g_app.results,&lvi); ListView_SetItemText(g_app.results,row,1,(LPWSTR)it.path.c_str()); ListView_SetItemText(g_app.results,row,2,(LPWSTR)it.size.c_str()); ListView_SetItemText(g_app.results,row,3,(LPWSTR)it.type.c_str()); ListView_SetItemText(g_app.results,row,4,(LPWSTR)it.modified.c_str()); }
std::vector<std::wstring> splitTabs(const std::wstring& line){ std::vector<std::wstring> p; std::wstring cur; for(wchar_t ch:line){ if(ch==L'\t'){ p.push_back(cur); cur.clear(); } else cur.push_back(ch);} p.push_back(cur); return p; }
void loadSearchResults(){ clearResults(); std::ifstream in(g_app.resultsPath,std::ios::binary); if(!in){ setStatus(L"Файл результатов не найден"); return;} std::string data((std::istreambuf_iterator<char>(in)),{}); std::wstring text=utf8ToWide(data); std::wistringstream ss(text); std::wstring line; int row=0; while(std::getline(ss,line)){ if(!line.empty()&&line.back()==L'\r') line.pop_back(); if(line.empty()) continue; auto p=splitTabs(line); if(p.size()<5) continue; ResultItem it{p[0],p[1],p[2],p[3],p[4]}; g_app.currentResults.push_back(it); addResultToList(g_app.currentResults.back(),row++);} std::wstringstream st; st<<L"Найдено: "<<row<<L" файлов"; setStatus(st.str()); }
std::wstring boolArg(bool v){ return v?L"true":L"false"; }
void runSearchAsync(){ std::wstring q=getText(g_app.queryEdit); if(q.empty()){ clearResults(); setStatus(L"Введите строку поиска"); return;} bool onlyName=SendMessageW(g_app.onlyNameCheck,BM_GETCHECK,0,0)==BST_CHECKED; bool caseSens=SendMessageW(g_app.caseCheck,BM_GETCHECK,0,0)==BST_CHECKED; if(!fs::exists(g_app.indexPath)){ showError(L"Индекс ещё не создан. Укажите папку и нажмите \"Запустить индексацию\"."); return;} EnableWindow(g_app.searchButton,FALSE); setStatus(L"Поиск..."); std::thread([q,onlyName,caseSens](){ fs::path indexer=g_app.appDir/L"FindFileIndexer.exe"; std::wstring root=readTextFile(g_app.rootPathFile); std::wstring cmd=quote(indexer.wstring())+L" search --index "+quote(g_app.indexPath.wstring())+L" --root "+quote(root)+L" --query "+quote(q)+L" --output "+quote(g_app.resultsPath.wstring())+L" --log "+quote((g_app.logsDir/L"indexer.log").wstring())+L" --limit 1000 --only-name "+boolArg(onlyName)+L" --case-sensitive "+boolArg(caseSens); DWORD code=0; runProcessWait(cmd,&code); PostMessageW(g_app.mainWindow,WM_APP_SEARCH_DONE,(WPARAM)code,0); }).detach(); }
void runIndexAsync(){ std::wstring root=getText(g_app.rootCombo); if(root.empty()){ showError(L"Введите путь к папке для индексации."); return;} if(!fs::exists(fs::path(root))){ showError(L"Путь недоступен или не существует:\n"+root); return;} addComboItem(root); saveSettings(); saveTextFile(g_app.rootPathFile,root); EnableWindow(g_app.startIndexButton,FALSE); EnableWindow(g_app.stopIndexButton,TRUE); setRootStatus(L"Статус: Индексация запущена..."); setStatus(L"Индексация..."); std::thread([root](){ fs::path indexer=g_app.appDir/L"FindFileIndexer.exe"; fs::path indexLog=g_app.logsDir/L"indexer.log"; std::wstring cmd=quote(indexer.wstring())+L" index --root "+quote(root)+L" --output "+quote(g_app.indexPath.wstring())+L" --log "+quote(indexLog.wstring())+L" --mode full"; DWORD code=0; runProcessWait(cmd,&code); PostMessageW(g_app.mainWindow,WM_APP_INDEX_DONE,(WPARAM)code,0); }).detach(); }
void stopIndexing(){ fs::path indexer=g_app.appDir/L"FindFileIndexer.exe"; DWORD code=0; runProcessWait(quote(indexer.wstring())+L" stop --session main",&code); setStatus(L"Команда остановки отправлена"); }
void checkRootPath(){ std::wstring root=getText(g_app.rootCombo); if(root.empty()){ setRootStatus(L"Статус: путь не указан"); return;} if(fs::exists(fs::path(root))){ setRootStatus(L"Статус: путь доступен"); addComboItem(root); saveSettings(); } else setRootStatus(L"Статус: путь недоступен"); }
void browseRoot(){ std::wstring p=pickFolder(); if(!p.empty()){ setText(g_app.rootCombo,p); checkRootPath(); } }
void openSelectedFile(bool folderOnly){ int sel=ListView_GetNextItem(g_app.results,-1,LVNI_SELECTED); if(sel<0||sel>=(int)g_app.currentResults.size()) return; fs::path p=g_app.currentResults[sel].path; if(folderOnly) ShellExecuteW(g_app.mainWindow,L"open",L"explorer.exe",(L"/select,"+quote(p.wstring())).c_str(),nullptr,SW_SHOWNORMAL); else ShellExecuteW(g_app.mainWindow,L"open",p.c_str(),nullptr,nullptr,SW_SHOWNORMAL); }
void copySelectedPath(){ int sel=ListView_GetNextItem(g_app.results,-1,LVNI_SELECTED); if(sel<0||sel>=(int)g_app.currentResults.size()) return; std::wstring path=g_app.currentResults[sel].path; if(!OpenClipboard(g_app.mainWindow)) return; EmptyClipboard(); SIZE_T bytes=(path.size()+1)*sizeof(wchar_t); HGLOBAL mem=GlobalAlloc(GMEM_MOVEABLE,bytes); if(mem){ void* ptr=GlobalLock(mem); memcpy(ptr,path.c_str(),bytes); GlobalUnlock(mem); SetClipboardData(CF_UNICODETEXT,mem);} CloseClipboard(); setStatus(L"Путь скопирован"); }
void checkUpdates(){ showInfo(L"Проверка обновлений будет включена после фикса LVKUpdater v0.1.1.\n\nПоиск и индексация уже вынесены в C++ движок."); }
void initColumns(){ ListView_SetExtendedListViewStyle(g_app.results,LVS_EX_FULLROWSELECT|LVS_EX_GRIDLINES|LVS_EX_DOUBLEBUFFER); struct C{const wchar_t* t; int w;}; C cols[]={{L"Имя",320},{L"Путь",520},{L"Размер",110},{L"Тип",140},{L"Дата изменения",170}}; for(int i=0;i<5;++i){ LVCOLUMNW c{}; c.mask=LVCF_TEXT|LVCF_WIDTH|LVCF_SUBITEM; c.pszText=(LPWSTR)cols[i].t; c.cx=scale(cols[i].w); c.iSubItem=i; ListView_InsertColumn(g_app.results,i,&c);} }
void layout(int w,int h){ int m=scale(16),gap=scale(10),top=scale(12),rootH=scale(118),panelW=scale(300),bh=scale(34),eh=scale(32),statusH=scale(26); int tabTop=top+rootH+gap; MoveWindow(g_app.rootGroup,m,top,w-m*3-panelW,rootH,TRUE); MoveWindow(g_app.indexGroup,w-m-panelW,top,panelW,rootH,TRUE); int rx=m+scale(14), ry=top+scale(28), rw=w-m*3-panelW-scale(28), comboW=rw-scale(250); MoveWindow(g_app.rootCombo,rx,ry,comboW,scale(300),TRUE); MoveWindow(g_app.browseButton,rx+comboW+gap,ry,scale(105),eh,TRUE); MoveWindow(g_app.checkRootButton,rx+comboW+gap+scale(115),ry,scale(105),eh,TRUE); MoveWindow(g_app.rootStatus,rx,ry+scale(46),rw,scale(26),TRUE); int ix=w-m-panelW+scale(16); MoveWindow(g_app.startIndexButton,ix,top+scale(30),panelW-scale(32),bh,TRUE); MoveWindow(g_app.stopIndexButton,ix,top+scale(72),panelW-scale(32),bh,TRUE); MoveWindow(g_app.tabs,m,tabTop,w-m*2,h-tabTop-statusH-m,TRUE); int cx=m+scale(16), cy=tabTop+scale(48), cw=w-m*2-scale(32); MoveWindow(g_app.queryLabel,cx,cy+scale(6),scale(105),scale(24),TRUE); MoveWindow(g_app.queryEdit,cx+scale(110),cy,scale(520),eh,TRUE); MoveWindow(g_app.onlyNameCheck,cx+scale(650),cy+scale(4),scale(150),scale(28),TRUE); MoveWindow(g_app.caseCheck,cx+scale(815),cy+scale(4),scale(170),scale(28),TRUE); MoveWindow(g_app.searchButton,cx+cw-scale(280),cy,scale(130),eh,TRUE); MoveWindow(g_app.clearButton,cx+cw-scale(140),cy,scale(130),eh,TRUE); MoveWindow(g_app.results,cx,cy+scale(58),cw,h-(cy+scale(58))-statusH-m-scale(8),TRUE); MoveWindow(g_app.statusBar,0,h-statusH,w,statusH,TRUE); ListView_SetColumnWidth(g_app.results,0,cw*30/100); ListView_SetColumnWidth(g_app.results,1,cw*36/100); ListView_SetColumnWidth(g_app.results,2,cw*9/100); ListView_SetColumnWidth(g_app.results,3,cw*12/100); ListView_SetColumnWidth(g_app.results,4,cw*13/100); }
HWND child(const wchar_t* cls,const wchar_t* text,DWORD st,DWORD ex,HWND parent,int id){ HWND h=CreateWindowExW(ex,cls,text,st,0,0,100,30,parent,(HMENU)(INT_PTR)id,g_app.instance,nullptr); applyFont(h); return h; }
void createControls(HWND hwnd){ g_app.rootGroup=child(L"BUTTON",L"Папка для индексации",WS_CHILD|WS_VISIBLE|BS_GROUPBOX,0,hwnd,0); g_app.rootCombo=child(WC_COMBOBOXW,L"",WS_CHILD|WS_VISIBLE|CBS_DROPDOWN|CBS_AUTOHSCROLL|WS_VSCROLL,WS_EX_CLIENTEDGE,hwnd,IDC_ROOT_COMBO); setText(g_app.rootCombo,L"Введите путь к папке или сетевой путь (пример: \\server\share или \\192.168.1.10\share)"); g_app.browseButton=child(L"BUTTON",L"Обзор...",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_BROWSE); g_app.checkRootButton=child(L"BUTTON",L"Проверить",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_CHECK_ROOT); g_app.rootStatus=child(L"STATIC",L"Статус: Готово к работе",WS_CHILD|WS_VISIBLE,0,hwnd,0); g_app.indexGroup=child(L"BUTTON",L"Индексация",WS_CHILD|WS_VISIBLE|BS_GROUPBOX,0,hwnd,0); g_app.startIndexButton=child(L"BUTTON",L"Запустить индексацию",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_START_INDEX); g_app.stopIndexButton=child(L"BUTTON",L"Остановить",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_STOP_INDEX); EnableWindow(g_app.stopIndexButton,FALSE); g_app.tabs=child(WC_TABCONTROLW,L"",WS_CHILD|WS_VISIBLE|WS_CLIPSIBLINGS,0,hwnd,IDC_TABS); TCITEMW tab{}; tab.mask=TCIF_TEXT; for(auto t:{L"Поиск",L"Результаты",L"Настройки",L"О программе"}){ tab.pszText=(LPWSTR)t; TabCtrl_InsertItem(g_app.tabs,TabCtrl_GetItemCount(g_app.tabs),&tab);} g_app.queryLabel=child(L"STATIC",L"Что искать:",WS_CHILD|WS_VISIBLE,0,hwnd,0); g_app.queryEdit=child(L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,WS_EX_CLIENTEDGE,hwnd,IDC_QUERY); g_app.onlyNameCheck=child(L"BUTTON",L"Только название",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,0,hwnd,IDC_ONLY_NAME); g_app.caseCheck=child(L"BUTTON",L"С учётом регистра",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,0,hwnd,IDC_CASE); g_app.searchButton=child(L"BUTTON",L"Найти",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_SEARCH); g_app.clearButton=child(L"BUTTON",L"Очистить",WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,0,hwnd,IDC_CLEAR); g_app.results=child(WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SHOWSELALWAYS,WS_EX_CLIENTEDGE,hwnd,IDC_RESULTS); initColumns(); g_app.statusBar=child(L"STATIC",L"Готово",WS_CHILD|WS_VISIBLE|SS_SUNKEN,0,hwnd,IDC_STATUS); }
void contextMenu(POINT pt){ int sel=ListView_GetNextItem(g_app.results,-1,LVNI_SELECTED); if(sel<0) return; HMENU m=CreatePopupMenu(); AppendMenuW(m,MF_STRING,IDC_OPEN_FILE,L"Открыть файл"); AppendMenuW(m,MF_STRING,IDC_OPEN_FOLDER,L"Открыть папку"); AppendMenuW(m,MF_SEPARATOR,0,nullptr); AppendMenuW(m,MF_STRING,IDC_COPY_PATH,L"Копировать путь"); TrackPopupMenu(m,TPM_RIGHTBUTTON,pt.x,pt.y,0,g_app.mainWindow,nullptr); DestroyMenu(m); }
LRESULT CALLBACK wndProc(HWND hwnd,UINT msg,WPARAM wp,LPARAM lp){ switch(msg){ case WM_CREATE: g_app.mainWindow=hwnd; g_app.dpi=GetDpiForWindow(hwnd); recreateFont(); createControls(hwnd); loadSettings(); layout(1200,760); logLine(L"FindFile started"); return 0; case WM_SIZE: layout(LOWORD(lp),HIWORD(lp)); return 0; case WM_DPICHANGED: g_app.dpi=HIWORD(wp); recreateFont(); if(auto r=(RECT*)lp) SetWindowPos(hwnd,nullptr,r->left,r->top,r->right-r->left,r->bottom-r->top,SWP_NOZORDER|SWP_NOACTIVATE); return 0; case WM_COMMAND: switch(LOWORD(wp)){ case IDC_BROWSE: browseRoot(); return 0; case IDC_CHECK_ROOT: checkRootPath(); return 0; case IDC_START_INDEX: runIndexAsync(); return 0; case IDC_STOP_INDEX: stopIndexing(); return 0; case IDC_SEARCH: runSearchAsync(); return 0; case IDC_CLEAR: clearResults(); SetWindowTextW(g_app.queryEdit,L""); return 0; case IDC_OPEN_FILE: openSelectedFile(false); return 0; case IDC_OPEN_FOLDER: openSelectedFile(true); return 0; case IDC_COPY_PATH: copySelectedPath(); return 0; } break; case WM_NOTIFY: if(((NMHDR*)lp)->hwndFrom==g_app.results){ NMHDR* h=(NMHDR*)lp; if(h->code==NM_DBLCLK){ openSelectedFile(false); return 0;} if(h->code==NM_RCLICK){ POINT pt{}; GetCursorPos(&pt); contextMenu(pt); return 0; }} break; case WM_APP_INDEX_DONE:{ DWORD code=(DWORD)wp; EnableWindow(g_app.startIndexButton,TRUE); EnableWindow(g_app.stopIndexButton,FALSE); if(code==0){ setRootStatus(L"Статус: Индекс создан"); setStatus(L"Индексация завершена. Введите запрос и нажмите Найти"); } else { std::wstringstream ss; ss<<L"Индексация завершилась с ошибкой. Код: "<<code<<L". См. logs\\indexer.log"; setStatus(ss.str()); setRootStatus(L"Статус: ошибка индексации"); showError(ss.str()); } return 0;} case WM_APP_SEARCH_DONE:{ DWORD code=(DWORD)wp; EnableWindow(g_app.searchButton,TRUE); if(code==0) loadSearchResults(); else { std::wstringstream ss; ss<<L"Поиск завершился с ошибкой. Код: "<<code<<L". См. logs\\gui.log"; setStatus(ss.str()); showError(ss.str()); } return 0;} case WM_DESTROY: saveSettings(); if(g_app.uiFont) DeleteObject(g_app.uiFont); PostQuitMessage(0); return 0;} return DefWindowProcW(hwnd,msg,wp,lp); }
}
int WINAPI wWinMain(HINSTANCE inst,HINSTANCE, PWSTR, int show){ CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED); INITCOMMONCONTROLSEX icc{sizeof(icc),ICC_LISTVIEW_CLASSES|ICC_TAB_CLASSES|ICC_STANDARD_CLASSES}; InitCommonControlsEx(&icc); g_app.instance=inst; g_app.appDir=exeDir(); ensureDirs(); WNDCLASSEXW wc{}; wc.cbSize=sizeof(wc); wc.hInstance=inst; wc.lpszClassName=L"FindFileNativeWindow"; wc.lpfnWndProc=wndProc; wc.hCursor=LoadCursorW(nullptr,IDC_ARROW); wc.hIcon=LoadIconW(nullptr,IDI_APPLICATION); wc.hIconSm=LoadIconW(nullptr,IDI_APPLICATION); wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1); RegisterClassExW(&wc); HWND hwnd=CreateWindowExW(0,wc.lpszClassName,L"FindFile",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,1280,800,nullptr,nullptr,inst,nullptr); if(!hwnd){ CoUninitialize(); return 1;} ShowWindow(hwnd,show); UpdateWindow(hwnd); MSG msg{}; while(GetMessageW(&msg,nullptr,0,0)>0){ TranslateMessage(&msg); DispatchMessageW(&msg);} CoUninitialize(); return (int)msg.wParam; }
